export { default as Bg } from "./bg/component"
export { default as Li } from "./li/component"
export { default as PopButton } from "./popbutton/component"
export { default as Section } from "./section/component"
export { default as Contact } from "./section/contact/component"
export { default as Experiences } from "./section/experiences/component"
export { default as Projects } from "./section/projects/component"
export { default as TechnologyStack } from "./section/technologystack/component"
